### ISSUE TITLE
Bug: Cannot delete tags in terraform destroy

### ISSUE THREAD

**Issue by Ghost---Shadow** [oracle-quickstart/oci-postgresql#17] opened 2021-09-17 04:11 UTC
Terraform destroy is not able to delete tags.

Steps to reproduce
1. terraform apply
2. terraform destroy

```
Error: 409-BadErrorResponse 
Provider version: 4.34.0, released on 2021-07-07. This provider is 10 update(s) behind to current.
Service: Bastion Session
Error Message: Failed to parse json from response body due to: json: cannot unmarshal number into Go struct field servicefailure.code of type string. With response body {
  "code" : 409,
  "message" : "resource is not allowed to delete with current state"
}.
OPC request ID: <masked>  
Suggestion: The resource is in a conflicted state. Please retry again or contact support for help with service: Bastion Session
````

Here is my terraform lock

```hcl
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/hashicorp/null" {
  version = "3.1.0"
  hashes = [
    "h1:vpC6bgUQoJ0znqIKVFevOdq+YQw42bRq0u+H3nto8nA=",
    "zh:02a1675fd8de126a00460942aaae242e65ca3380b5bb192e8773ef3da9073fd2",
    "zh:53e30545ff8926a8e30ad30648991ca8b93b6fa496272cd23b26763c8ee84515",
    "zh:5f9200bf708913621d0f6514179d89700e9aa3097c77dac730e8ba6e5901d521",
    "zh:9ebf4d9704faba06b3ec7242c773c0fbfe12d62db7d00356d4f55385fc69bfb2",
    "zh:a6576c81adc70326e4e1c999c04ad9ca37113a6e925aefab4765e5a5198efa7e",
    "zh:a8a42d13346347aff6c63a37cda9b2c6aa5cc384a55b2fe6d6adfa390e609c53",
    "zh:c797744d08a5307d50210e0454f91ca4d1c7621c68740441cf4579390452321d",
    "zh:cecb6a304046df34c11229f20a80b24b1603960b794d68361a67c5efe58e62b8",
    "zh:e1371aa1e502000d9974cfaff5be4cfa02f47b17400005a16f14d2ef30dc2a70",
    "zh:fc39cc1fe71234a0b0369d5c5c7f876c71b956d23d7d6f518289737a001ba69b",
    "zh:fea4227271ebf7d9e2b61b89ce2328c7262acd9fd190e1fd6d15a591abfa848e",
  ]
}

provider "registry.terraform.io/hashicorp/oci" {
  version     = "4.34.0"
  constraints = "4.34.0"
  hashes = [
    "h1:wBx629lse/pvbKHc4K+/kmSTwXVE17Ct0xA65M5nTNI=",
    "zh:13877dff9643393f013f771527fd9aade06f91442cbc6c0f1df4042c48983b05",
    "zh:97425682bedbc86b3a036e99bf443c25a27f62418dd7061384cd6d5992098b16",
    "zh:9e41262cd26303ea2fb239ac1d32c4f94814bed7acf395d850862fba8476d915",
    "zh:ac2a0ce6157412d7a508f7e8c05917c7637559d5ade1e58c554969d062a0449f",
    "zh:b9717dbda12a2cb273cf00b5089b4352634980c63fa615b6a97e6e378058131a",
    "zh:ba7bef6ca6d77a0eef79d3123a938a893269d852867e0f0f8c7937f5718de20c",
    "zh:d509cb7a671ba2cfde554bdc2c32c54325657a45110d7447640f5a50a6108e05",
    "zh:e598b18cc7d9d78fcb987d1ab33b9665ba973984c867bfdb822f7405e695fe45",
    "zh:fab9b570a73d5ad6a6a25e501305396890e5f8d81782d4ed5bce10c5e5964a90",
    "zh:fb91e30619f879b2316847a7a680ab92c2b8b81955db9337c97e7ae8edf308bf",
  ]
}

provider "registry.terraform.io/hashicorp/random" {
  version = "3.1.0"
  hashes = [
    "h1:BZMEPucF+pbu9gsPk0G0BHx7YP04+tKdq2MrRDF1EDM=",
    "zh:2bbb3339f0643b5daa07480ef4397bd23a79963cc364cdfbb4e86354cb7725bc",
    "zh:3cd456047805bf639fbf2c761b1848880ea703a054f76db51852008b11008626",
    "zh:4f251b0eda5bb5e3dc26ea4400dba200018213654b69b4a5f96abee815b4f5ff",
    "zh:7011332745ea061e517fe1319bd6c75054a314155cb2c1199a5b01fe1889a7e2",
    "zh:738ed82858317ccc246691c8b85995bc125ac3b4143043219bd0437adc56c992",
    "zh:7dbe52fac7bb21227acd7529b487511c91f4107db9cc4414f50d04ffc3cab427",
    "zh:a3a9251fb15f93e4cfc1789800fc2d7414bbc18944ad4c5c98f466e6477c42bc",
    "zh:a543ec1a3a8c20635cf374110bd2f87c07374cf2c50617eee2c669b3ceeeaa9f",
    "zh:d9ab41d556a48bd7059f0810cf020500635bfc696c9fc3adab5ea8915c1d886b",
    "zh:d9e13427a7d011dbd654e591b0337e6074eef8c3b9bb11b2e39eaaf257044fd7",
    "zh:f7605bd1437752114baf601bdf6931debe6dc6bfe3006eb7e9bb9080931dca8a",
  ]
}

provider "registry.terraform.io/hashicorp/template" {
  version = "2.2.0"
  hashes = [
    "h1:94qn780bi1qjrbC3uQtjJh3Wkfwd5+tTtJHOb7KTg9w=",
    "zh:01702196f0a0492ec07917db7aaa595843d8f171dc195f4c988d2ffca2a06386",
    "zh:09aae3da826ba3d7df69efeb25d146a1de0d03e951d35019a0f80e4f58c89b53",
    "zh:09ba83c0625b6fe0a954da6fbd0c355ac0b7f07f86c91a2a97849140fea49603",
    "zh:0e3a6c8e16f17f19010accd0844187d524580d9fdb0731f675ffcf4afba03d16",
    "zh:45f2c594b6f2f34ea663704cc72048b212fe7d16fb4cfd959365fa997228a776",
    "zh:77ea3e5a0446784d77114b5e851c970a3dde1e08fa6de38210b8385d7605d451",
    "zh:8a154388f3708e3df5a69122a23bdfaf760a523788a5081976b3d5616f7d30ae",
    "zh:992843002f2db5a11e626b3fc23dc0c87ad3729b3b3cff08e32ffb3df97edbde",
    "zh:ad906f4cebd3ec5e43d5cd6dc8f4c5c9cc3b33d2243c89c5fc18f97f7277b51d",
    "zh:c979425ddb256511137ecd093e23283234da0154b7fa8b21c2687182d9aea8b2",
  ]
}

provider "registry.terraform.io/hashicorp/tls" {
  version = "3.1.0"
  hashes = [
    "h1:fUJX8Zxx38e2kBln+zWr1Tl41X+OuiE++REjrEyiOM4=",
    "zh:3d46616b41fea215566f4a957b6d3a1aa43f1f75c26776d72a98bdba79439db6",
    "zh:623a203817a6dafa86f1b4141b645159e07ec418c82fe40acd4d2a27543cbaa2",
    "zh:668217e78b210a6572e7b0ecb4134a6781cc4d738f4f5d09eb756085b082592e",
    "zh:95354df03710691773c8f50a32e31fca25f124b7f3d6078265fdf3c4e1384dca",
    "zh:9f97ab190380430d57392303e3f36f4f7835c74ea83276baa98d6b9a997c3698",
    "zh:a16f0bab665f8d933e95ca055b9c8d5707f1a0dd8c8ecca6c13091f40dc1e99d",
    "zh:be274d5008c24dc0d6540c19e22dbb31ee6bfdd0b2cddd4d97f3cd8a8d657841",
    "zh:d5faa9dce0a5fc9d26b2463cea5be35f8586ab75030e7fa4d4920cd73ee26989",
    "zh:e9b672210b7fb410780e7b429975adcc76dd557738ecc7c890ea18942eb321a5",
    "zh:eb1f8368573d2370605d6dbf60f9aaa5b64e55741d96b5fb026dbfe91de67c0d",
    "zh:fc1e12b713837b85daf6c3bb703d7795eaf1c5177aebae1afcf811dd7009f4b0",
  ]
}
```

**Comment by lfeldman** [comment] 2021-09-17 11:09
@Ghost---Shadow thanks for the update. We will try to troubleshoot that.

**Comment by lfeldman** [comment] 2021-09-28 10:25
@Ghost---Shadow we were not able to reproduce your issue. Any additional details for further troubleshooting?

**Comment by Ghost---Shadow** [comment] 2021-09-29 12:38
I am not sure. We can close the issue. It is not a breaking bug.

**Comment by lfeldman** [comment] 2021-09-29 15:43
Ok. Closing the ticket.

**Closed by lfeldman** 2021-09-29 15:43 UTC
